project:
  type: website 
  output-dir: docs

website:
  title: "Sakura's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



